apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: workout-tracker-pipeline
description: main application pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []
  - targetId: staging
    profiles: []
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: dev target
run:
  location: projects/haroonc-exp/locations/us-central1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
description: staging target
run:
  location: projects/haroonc-exp/locations/us-central1
